default_language_version:
  python: python3

default_stages: [manual]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-merge-conflict
        name: check-merge-conflict
        description: Check for files that contain merge conflict strings.

    -   id: trailing-whitespace
        name: trailing-whitespace
        description: Remove all trailing whitespace from the code

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
    -   id: ruff
        args:
        -   --fix
        exclude: 'pypsa_canada/workflow/rules/*'
    -   id: ruff-format
        exclude: 'pypsa_canada/workflow/rules/*'

# -   repo: https://github.com/DavidAnson/markdownlint-cli2
#     rev: v0.22.0
#     hooks:
#         - id: markdownlint-cli2
